# 1. Get 방식

# Get방식에서 파라미터 없는 경우
#GET localhost:7080/get-api/hello

# Get방식에서 사용된 {변수}의 이름과 메소드의 매개변수와 일치시킨 경우
#GET localhost:7080/get-api/var1/hello

# Get방식에서 사용된 {변수}의 이름과 메소드의 매개변수와 다를 경우
#GET localhost:7080/get-api/var2/hello

# Get방식에서 '?'를 기준으로 우측에 {키} = {값}의 형태로 전달되며, 복수 형태로 전달할 경우 & 를 사용함
#GET localhost:7080/get-api/request1?name=haryang&email=a@gmail.com&organization=thinkdev

# Get방식에서 어떤 요청 값이 들어올지 모를 경우 사용하는 방식
#GET localhost:7080/get-api/request2?name=haryang&email=a@gmail.com&organization=thinkdev

# GET방식에서 key와 value가 정해져있지만, 받아야할 파라미터가 많을 경우 DTO 객체를 사용한 방식
#GET localhost:7080/get-api/request3?name=haryang&email=a@gmail.com&organization=thinkdev

ifconfig.me
